"""latest migration

Revision ID: 04cf9ad17ddd
Revises: add_expired_to_invitationstatus
Create Date: 2025-09-03 09:36:51.313078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04cf9ad17ddd'
down_revision: Union[str, Sequence[str], None] = 'add_expired_to_invitationstatus'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'invitation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('orders_invitation_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'invitations', ['invitation_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_invitation_id_fkey'), 'orders', 'invitations', ['invitation_id'], ['id'])
    op.alter_column('orders', 'invitation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
