"""init schema

Revision ID: 1830a416656c
Revises: 5ad2a74b895d
Create Date: 2025-08-31 05:48:55.046463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1830a416656c'
down_revision: Union[str, Sequence[str], None] = '5ad2a74b895d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('main_guest_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'guests', 'guests', ['main_guest_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'guests', type_='foreignkey')
    op.drop_column('guests', 'main_guest_id')
    # ### end Alembic commands ###
