"""init schema

Revision ID: 1b7b12a1e120
Revises: ec1e5b10ac91
Create Date: 2025-08-31 07:47:07.879467

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1b7b12a1e120"
down_revision: Union[str, Sequence[str], None] = "ec1e5b10ac91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add 'created_at' with default for existing rows
    op.add_column(
        "guests",
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.now(),  # ensures existing rows are populated
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("guests", "created_at")
    # ### end Alembic commands ###
