"""latest migration

Revision ID: 21321f559d00
Revises: e1a7d98bb895
Create Date: 2025-09-01 08:59:49.173365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21321f559d00'
down_revision: Union[str, Sequence[str], None] = 'e1a7d98bb895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fallback_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fallback_currency', sa.String(length=3), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_tiers_id'), 'price_tiers', ['id'], unique=False)
    op.add_column('orders', sa.Column('price_tier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'price_tiers', ['price_tier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'price_tier_id')
    op.drop_index(op.f('ix_price_tiers_id'), table_name='price_tiers')
    op.drop_table('price_tiers')
    # ### end Alembic commands ###
