"""latest migration

Revision ID: 38a211d38098
Revises: 91070eaa4805
Create Date: 2025-09-01 06:37:44.093825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38a211d38098'
down_revision: Union[str, Sequence[str], None] = '91070eaa4805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fonts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('font_family', sa.String(length=100), nullable=False),
    sa.Column('font_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_index(op.f('ix_fonts_id'), 'fonts', ['id'], unique=False)
    op.add_column('invitations', sa.Column('font_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('invitations_template_id_fkey'), 'invitations', type_='foreignkey')
    op.create_foreign_key(None, 'invitations', 'fonts', ['font_id'], ['id'])
    op.drop_column('invitations', 'font')
    op.drop_column('invitations', 'template_id')
    op.add_column('templates', sa.Column('font_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'templates', 'fonts', ['font_id'], ['id'])
    op.drop_column('templates', 'font')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('font', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'templates', type_='foreignkey')
    op.drop_column('templates', 'font_id')
    op.add_column('invitations', sa.Column('template_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('invitations', sa.Column('font', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.create_foreign_key(op.f('invitations_template_id_fkey'), 'invitations', 'templates', ['template_id'], ['id'])
    op.drop_column('invitations', 'font_id')
    op.drop_index(op.f('ix_fonts_id'), table_name='fonts')
    op.drop_table('fonts')
    # ### end Alembic commands ###
