"""latest migration

Revision ID: 3de5b52c7538
Revises: 71586e7ea084
Create Date: 2025-09-09 06:26:24.524292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3de5b52c7538'
down_revision: Union[str, Sequence[str], None] = '71586e7ea084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('presentation_image', sa.String(), nullable=True))
    op.drop_column('games', 'video')
    op.drop_column('invitations', 'video_file')
    op.add_column('slideshows', sa.Column('presentation_image', sa.String(), nullable=True))
    op.drop_column('slideshows', 'video')
    op.drop_column('templates', 'video_file')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('video_file', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('slideshows', sa.Column('video', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('slideshows', 'presentation_image')
    op.add_column('invitations', sa.Column('video_file', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('video', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('games', 'presentation_image')
    # ### end Alembic commands ###
