"""latest migration

Revision ID: 48f83e5c29ed
Revises: 9645e9ff3b06
Create Date: 2025-09-12 06:10:47.457147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48f83e5c29ed'
down_revision: Union[str, Sequence[str], None] = '9645e9ff3b06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_user_stats', sa.Column('unique_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('uq_date_user_type'), 'daily_user_stats', type_='unique')
    op.create_index(op.f('ix_daily_user_stats_unique_id'), 'daily_user_stats', ['unique_id'], unique=False)
    op.create_unique_constraint('uq_date_unique_user', 'daily_user_stats', ['date', 'unique_id'])
    op.drop_column('daily_user_stats', 'active_count')
    op.drop_column('daily_user_stats', 'user_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_user_stats', sa.Column('user_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('daily_user_stats', sa.Column('active_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_date_unique_user', 'daily_user_stats', type_='unique')
    op.drop_index(op.f('ix_daily_user_stats_unique_id'), table_name='daily_user_stats')
    op.create_unique_constraint(op.f('uq_date_user_type'), 'daily_user_stats', ['date', 'user_type'], postgresql_nulls_not_distinct=False)
    op.drop_column('daily_user_stats', 'unique_id')
    # ### end Alembic commands ###
