"""latest migration

Revision ID: 575edd2a0142
Revises: 96349002bc64
Create Date: 2025-09-03 06:20:22.489179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '575edd2a0142'
down_revision: Union[str, Sequence[str], None] = '96349002bc64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'company_identifier')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('company_identifier', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
