"""latest migration

Revision ID: 578416e0f77c
Revises: 914748bab1b7
Create Date: 2025-09-07 07:55:23.254468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '578416e0f77c'
down_revision: Union[str, Sequence[str], None] = '914748bab1b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slideshow_images', sa.Column('template_id', sa.Integer(), nullable=True))
    op.alter_column('slideshow_images', 'invitation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'slideshow_images', 'templates', ['template_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'slideshow_images', type_='foreignkey')
    op.alter_column('slideshow_images', 'invitation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('slideshow_images', 'template_id')
    # ### end Alembic commands ###
