"""latest migration

Revision ID: 5af360331f54
Revises: 96e1635d0c70
Create Date: 2025-09-14 11:35:00.526577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5af360331f54'
down_revision: Union[str, Sequence[str], None] = '96e1635d0c70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('invitations_preview_token_key'), 'invitations', type_='unique')
    op.drop_column('invitations', 'preview_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('preview_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('invitations_preview_token_key'), 'invitations', ['preview_token'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
