"""latest migration

Revision ID: 5eee1531c6f9
Revises: c6161484f247
Create Date: 2025-09-11 03:51:04.311736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eee1531c6f9'
down_revision: Union[str, Sequence[str], None] = 'c6161484f247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcategory_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('subcategory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_subcategory_variants_id'), 'subcategory_variants', ['id'], unique=False)
    op.alter_column('blog_posts', 'slug',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog_posts', 'slug',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.drop_index(op.f('ix_subcategory_variants_id'), table_name='subcategory_variants')
    op.drop_table('subcategory_variants')
    # ### end Alembic commands ###
