"""latest migration

Revision ID: 82c3552ae421
Revises: 21321f559d00
Create Date: 2025-09-01 11:30:43.480560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82c3552ae421'
down_revision: Union[str, Sequence[str], None] = '21321f559d00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_tiers', 'fallback_price')
    op.drop_column('price_tiers', 'fallback_currency')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_tiers', sa.Column('fallback_currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False))
    op.add_column('price_tiers', sa.Column('fallback_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
