"""latest migration

Revision ID: 87589cb28bef
Revises: 6efa7fb9a7a9
Create Date: 2025-09-01 15:29:06.755934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87589cb28bef'
down_revision: Union[str, Sequence[str], None] = '6efa7fb9a7a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('invitation_wallpaper', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'invitation_wallpaper')
    # ### end Alembic commands ###
