"""latest migration

Revision ID: 914748bab1b7
Revises: b787fad14697
Create Date: 2025-09-07 07:34:33.492363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '914748bab1b7'
down_revision: Union[str, Sequence[str], None] = 'b787fad14697'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('video_file', sa.String(), nullable=True))
    op.add_column('templates', sa.Column('video_file', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'video_file')
    op.drop_column('invitations', 'video_file')
    # ### end Alembic commands ###
