"""latest migration

Revision ID: 96349002bc64
Revises: 87589cb28bef
Create Date: 2025-09-03 06:15:03.905272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96349002bc64'
down_revision: Union[str, Sequence[str], None] = '87589cb28bef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('company_identifier', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'company_identifier')
    # ### end Alembic commands ###
