"""latest migration

Revision ID: 9645e9ff3b06
Revises: 5eee1531c6f9
Create Date: 2025-09-11 03:59:18.062887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9645e9ff3b06'
down_revision: Union[str, Sequence[str], None] = '5eee1531c6f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('subcategory_variant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'templates', 'subcategory_variants', ['subcategory_variant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'templates', type_='foreignkey')
    op.drop_column('templates', 'subcategory_variant_id')
    # ### end Alembic commands ###
