"""latest migration

Revision ID: 96e1635d0c70
Revises: 48f83e5c29ed
Create Date: 2025-09-13 11:22:17.343948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96e1635d0c70'
down_revision: Union[str, Sequence[str], None] = '48f83e5c29ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('first_page', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'first_page')
    # ### end Alembic commands ###
