"""init schema

Revision ID: a434693bcd69
Revises: 9c2ca3053918
Create Date: 2025-08-29 10:34:00.860372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a434693bcd69'
down_revision: Union[str, Sequence[str], None] = '9c2ca3053918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'invitations', ['rsvp_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invitations', type_='unique')
    # ### end Alembic commands ###
