"""init schema

Revision ID: a98927f9911c
Revises: a434693bcd69
Create Date: 2025-08-29 10:36:55.968726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a98927f9911c'
down_revision: Union[str, Sequence[str], None] = 'a434693bcd69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('invitations_rsvp_id_fkey'), 'invitations', type_='foreignkey')
    op.create_foreign_key(None, 'invitations', 'rsvps', ['rsvp_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.create_foreign_key(op.f('invitations_rsvp_id_fkey'), 'invitations', 'rsvps', ['rsvp_id'], ['id'])
    # ### end Alembic commands ###
