"""latest migration

Revision ID: b787fad14697
Revises: b6ad1696f80b
Create Date: 2025-09-07 06:55:27.637117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b787fad14697'
down_revision: Union[str, Sequence[str], None] = 'b6ad1696f80b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('video', sa.String(), nullable=True))
    op.add_column('slideshows', sa.Column('video', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slideshows', 'video')
    op.drop_column('games', 'video')
    # ### end Alembic commands ###
