"""latest migration

Revision ID: c35d5d323d11
Revises: 38a211d38098
Create Date: 2025-09-01 07:20:03.741460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c35d5d323d11'
down_revision: Union[str, Sequence[str], None] = '38a211d38098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('selected_font', sa.String(), nullable=True))
    op.drop_constraint(op.f('invitations_font_id_fkey'), 'invitations', type_='foreignkey')
    op.drop_column('invitations', 'font_id')
    op.add_column('templates', sa.Column('selected_font', sa.String(), nullable=True))
    op.drop_constraint(op.f('templates_font_id_fkey'), 'templates', type_='foreignkey')
    op.drop_column('templates', 'font_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('font_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('templates_font_id_fkey'), 'templates', 'fonts', ['font_id'], ['id'])
    op.drop_column('templates', 'selected_font')
    op.add_column('invitations', sa.Column('font_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('invitations_font_id_fkey'), 'invitations', 'fonts', ['font_id'], ['id'])
    op.drop_column('invitations', 'selected_font')
    # ### end Alembic commands ###
