"""latest migration

Revision ID: cf3a3ed42bb7
Revises: d50b10c71689
Create Date: 2025-08-31 09:28:15.418743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf3a3ed42bb7'
down_revision: Union[str, Sequence[str], None] = 'd50b10c71689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guests', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_guest_full_name_gist'), table_name='guests', postgresql_ops={'full_name': 'gist_trgm_ops'}, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_guest_full_name_gist'), 'guests', ['full_name'], unique=False, postgresql_ops={'full_name': 'gist_trgm_ops'}, postgresql_using='gist')
    op.alter_column('guests', 'full_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
