"""init schema

Revision ID: e0ed8423155a
Revises: ec3523d858d2
Create Date: 2025-08-23 06:41:52.066673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0ed8423155a'
down_revision: Union[str, Sequence[str], None] = 'ec3523d858d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_user_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('user_type', sa.String(), nullable=True),
    sa.Column('active_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_user_stats_date'), 'daily_user_stats', ['date'], unique=False)
    op.create_index(op.f('ix_daily_user_stats_id'), 'daily_user_stats', ['id'], unique=False)
    op.drop_index(op.f('ix_user_activity_id'), table_name='user_activity')
    op.drop_index(op.f('ix_user_activity_timestamp'), table_name='user_activity')
    op.drop_index(op.f('ix_user_activity_user_id'), table_name='user_activity')
    op.drop_table('user_activity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activity',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activity_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_activity_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_activity_pkey'))
    )
    op.create_index(op.f('ix_user_activity_user_id'), 'user_activity', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_activity_timestamp'), 'user_activity', ['timestamp'], unique=False)
    op.create_index(op.f('ix_user_activity_id'), 'user_activity', ['id'], unique=False)
    op.drop_index(op.f('ix_daily_user_stats_id'), table_name='daily_user_stats')
    op.drop_index(op.f('ix_daily_user_stats_date'), table_name='daily_user_stats')
    op.drop_table('daily_user_stats')
    # ### end Alembic commands ###
