"""latest migration

Revision ID: ee71dc44ceba
Revises: 3de5b52c7538
Create Date: 2025-09-09 10:24:04.455454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee71dc44ceba'
down_revision: Union[str, Sequence[str], None] = '3de5b52c7538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_date_user_type', 'daily_user_stats', ['date', 'user_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_date_user_type', 'daily_user_stats', type_='unique')
    # ### end Alembic commands ###
